name: Update GitHub Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Atualizar README com GitHub Stats
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api?username=Cleiltonss&show_icons=true&theme=radical"
      
      - name: Commit e Push se Alterado
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main || echo "Nenhuma atualização para pull"
          git add README.md
          git commit -m "Atualizar GitHub Stats [Automático]" || echo "Nada para comitar"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
